table Categoria
	lineageTag: d068f48e-34a3-4d64-b919-fea23b0006fe

	column Categoria
		dataType: string
		lineageTag: 7ba6e478-a777-452f-ad80-f051436bbe5c
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Cat-Otros
		dataType: string
		lineageTag: 5e2d4121-d78a-429c-9057-9701b147478c
		summarizeBy: none
		sourceColumn: Cat-Otros

		annotation SummarizationSetBy = Automatic

	partition Categoria = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("VcxBCgIxDIXhq0jXcwtxLYyzK7MonScE2hfJRM9vVRSzS76fJOd0ZhMiTd9hnXKa0e+ElSrKV3HT/R2O2mUrgU4N1U3q8C0GusFB6QK6hjYPKYdAF9hjfBnbvy5ouCrj9WKF+03NEfgz/WR9Ag==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Categoria = _t, #"Cat-Otros" = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Categoria", type text}, {"Cat-Otros", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

